export const IMAGES_LOADING = 'IMAGES_LOADING';
export const IMAGES_ADD = 'IMAGES_ADD';
export const IMAGES_LOADING_FAILED = 'IMAGES_LOADING_FAILED';
export const FETCH_IMAGES = 'FETCH_IMAGES';
export const INITIAL_STATE = 'INITIAL_STATE';
